version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  db-seeds:
    build: ./services/mongo-seeds
    links:
      - db

  curb-gateway:
    build: ./services/gateway
    ports:
      - 4000:4000
    depends_on:
      - curb-accounts
      - curb-users
      - curb-groups
      - curb-contents
      - curb-emailing

  curb-users:
    build: ./services/users
    ports:
      - 4003:4000
    depends_on:
      - db

  curb-accounts:
    build: ./services/accounts
    ports:
      - 4001:4000
    depends_on:
      - db

  curb-groups:
    build: ./services/groups
    ports:
      - 4002:4000
    depends_on:
      - db

  curb-contents:
    build: ./services/contents
    ports:
      - 4004:4000
    depends_on:
      - db
  curb-emailing:
    build: ./services/emailing
    ports:
      - 4005:4000
    depends_on:
      - db
