version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  db-seeds:
    build: ./services/mongo-seeds
    links:
      - db

  curb-gateway:
    build: ./services/gateway
    image: eliasdem/curb-gateway
    ports:
      - 4000:4000
    depends_on:
      - curb-accounts
      - curb-users
      - curb-groups
      - curb-contents
      - curb-emailing

  curb-users:
    build: ./services/users
    image: eliasdem/curb-users
    ports:
      - 4003:4000
    depends_on:
      - db

  curb-accounts:
    build: ./services/accounts
    image: eliasdem/curb-accounts
    ports:
      - 4001:4000
    depends_on:
      - db

  curb-groups:
    build: ./services/groups
    image: eliasdem/curb-groups
    ports:
      - 4002:4000
    depends_on:
      - db

  curb-contents:
    build: ./services/contents
    image: eliasdem/curb-contents
    ports:
      - 4004:4000
    depends_on:
      - db

  curb-emailing:
    build: ./services/emailing
    image: eliasdem/curb-emailing
    ports:
      - 4005:4000
    depends_on:
      - db

  curb-chat:
    build: ./services/chat
    image: eliasdem/curb-chat
    ports:
      - 4006:4000
    depends_on:
      - db
  
  curb-notif:
    build: ./services/notif
    image: eliasdem/curb-notif
    ports:
      - 4007:4000
    depends_on:
      - db
