version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  db-seeds:
    build: ./services/mongo-seeds
    links:
      - db

  curb-gateway:
    build: ./services/gateway
    ports:
      - 4000:4000
    depends_on:
      - curb-accounts
      - curb-users
      - curb-groups
      - curb-content

  curb-users:
    build: ./services/users
    ports:
      - 4003:4000
    depends_on:
      - db

  curb-accounts:
    build: ./services/accounts
    ports:
      - 4001:4000
    depends_on:
      - db

  curb-groups:
    build: ./services/groups
    ports:
      - 4002:4000
<<<<<<< HEAD
    depends_on:
      - db

  curb-content:
    build: ./services/group-content
    ports:
      - 4004:4000
=======
>>>>>>> 76d89126175ea271dfcc94eea9803905b92e4df3
    depends_on:
      - db
