version: '3'

services:
  db:
    image: mongo
    ports:
      - 27017:27017

  db-seeds:
    build: ./services/mongo-seeds
    links:
      - db

  curb-gateway:
    build: ./services/gateway
    ports:
      - 3000:3000
    depends_on:
      - curb-accounts
      - curb-users

  curb-users:
    build: ./services/users
    ports:
      - 3003:3000
    depends_on:
      - db

  curb-accounts:
    build: ./services/accounts
    ports:
      - 3001:3000
    depends_on:
      - db
