module.exports = {
  CONTENTS_BAD_PARAMETER: 400,
  CONTENTS_INVALID_ID: 400,
  CONTENTS_MISSING_CREATOR_ID: 400,
  CONTENTS_MISSING_GROUP_ID: 400,
  CONTENTS_MISSING_TYPE: 400,
  CONTENTS_ALREADY_EXIST: 400,
  CONTENTS_INVALID_TYPE: 400,
  CONTENTS_FORBIDDEN_WRITE: 403,
  CONTENTS_NOT_GROUP_CREATOR: 403,
  CONTENTS_INEXISTENT_CONTENT: 404,
  CONTENTS_CONTENTS_DATABASE_ERROR: 500
};
